version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: watch
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
      - "./bin:/app/bin"
      - "./obj:/app/obj"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=admin
      - ACCEPT_EULA=Y
    volumes:
      - ./data:/var/opt/mssql/data   
    ports:
      - "1450:1433"