version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    ports:
      - "5000:5000"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: Admin#2023
      ACCEPT_EULA: Y
