version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
    container_name: psiuweb_devcontainer
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: Admin#2023
      ACCEPT_EULA: Y
